#!/bin/zsh
# Builds a firmware, embeds its bootloader + partition table into a migrator project, builds the migrator.
# Usage: build_migrator.sh <firmware-project-dir> <migrator-project-dir> <out-dir> [extra idf.py args for both builds]
# Output: <out-dir>/<firmware>.bin, <out-dir>/<migrator>.bin (+ .sha256). Fails if the migrator exceeds 1 MB.
set -eo pipefail
FW=${1:A}; MIG=${2:A}; OUT=${3:A}; shift 3
source ~/.espressif/tools/activate_idf_v5.4.2.sh >/dev/null 2>&1 || true
IDF=("$IDF_PYTHON_ENV_PATH/bin/python" "$IDF_PATH/tools/idf.py")

(cd "$FW" && "${IDF[@]}" "$@" build >/dev/null)
mkdir -p "$MIG/blobs" "$OUT"
cp "$FW/build/bootloader/bootloader.bin" "$FW/build/partition_table/partition-table.bin" "$MIG/blobs/"

python3 - "$MIG/blobs" <<'PY'
import hashlib, os, sys
d = sys.argv[1]
def entry(name, macro):
    data = open(os.path.join(d, name), "rb").read()
    sha = ", ".join(f"0x{b:02x}" for b in hashlib.sha256(data).digest())
    return f"#define {macro}_LEN {len(data)}\n#define {macro}_SHA256 {{ {sha} }}\n"
with open(os.path.join(d, "blobs_manifest.h"), "w") as f:
    f.write("#pragma once\n/* Generated by home-idf tools/build_migrator.sh: expected embedded blobs */\n")
    f.write(entry("bootloader.bin", "BLOB_BOOTLOADER"))
    f.write(entry("partition-table.bin", "BLOB_PARTITION_TABLE"))
PY

(cd "$MIG" && "${IDF[@]}" "$@" build >/dev/null)
app_bin() { python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d["build_dir"] + "/" + d["app_bin"])' "$1/build/project_description.json"; }
fw_bin=$(app_bin "$FW")
mig_bin=$(app_bin "$MIG")
cp "$fw_bin" "$mig_bin" "$OUT/"
for f in "$OUT/${fw_bin:t}" "$OUT/${mig_bin:t}"; do shasum -a 256 "$f" | tee "$f.sha256"; done
size=$(stat -f%z "$OUT/${mig_bin:t}")
(( size <= 1048576 )) || { echo "migrator does not fit a legacy 1 MB slot: $size B"; exit 1; }
